#!/usr/bin/env python3
"""Validate a design-forge corpus and regenerate its index.

Standard library only, and deliberately so: a skill runs on machines nobody
configured for it, so this must not need pyyaml, uv, or a virtualenv. The
frontmatter parser below understands exactly the shapes the contract defines --
scalars, booleans, and flat lists of them -- and fails closed by naming the file
and line when it meets anything else. It is not a YAML implementation and MUST
NOT grow into one.

Line length is 88 rather than the 120 the house Python style prefers, because
pre-commit runs ruff with its defaults over `skills/` and repo-local hygiene
wins. NamedTuple rather than attrs or dataclasses, because attrs would be a
runtime dependency this script cannot assume.

Nothing here raises on corpus content. Every problem is accumulated and reported
at once, so one malformed document does not hide the other nine. Exit status is
1 on contract errors and 0 on warnings, because length ceilings warn and propose
but never block.
"""

from __future__ import annotations

import argparse
import difflib
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import NamedTuple

#: A frontmatter leaf value, after the restricted parse.
Scalar = str | bool
#: A frontmatter field value: a leaf, or a flat list of them.
FrontValue = Scalar | list[Scalar]
#: One document's parsed frontmatter block.
Frontmatter = dict[str, FrontValue]

LIFECYCLES = ("draft", "active", "stale", "superseded")
KNOWN_KEYS = (
    "type",
    "lifecycle",
    "owns",
    "locked",
    "superseded-by",
    "supersedes",
    "handling",
)
# Fixed, unlike `type`. The whole point of the field is to be a signal, and a
# freeform value means a typo silently disables it. Spelling is all this script
# can check -- nothing here enforces the restriction itself.
HANDLING_VALUES = ("internal", "customer-confidential", "third-party")
SECTION_WARN_LINES = 200
DOC_WARN_LINES = 1000
DOC_LIMIT_LINES = 2000
AMENDMENT_WARN_COUNT = 5
# A stale index usually differs in one or two rows. Printing a hundred turns a
# actionable report into a wall nobody reads, so the rest are counted instead.
INDEX_DRIFT_MAX = 10

INDEX_MARKER = "<!-- generated by design-forge check_corpus.py; do not edit -->"
AMENDMENT_ENTRY = re.compile(r"^###\s+A(\d+)\b")
AMENDMENT_MARKER = re.compile(r"\[amended A(\d+)\]")
SKIP_DIRS = frozenset({".git", ".venv", "node_modules", "__pycache__"})

EXIT_OK = 0
EXIT_CONTRACT_ERRORS = 1
EXIT_BAD_USAGE = 2


class Doc(NamedTuple):
    """One parsed corpus document.

    Attributes:
        path: Absolute or invocation-relative path to the file.
        rel: Path relative to the corpus root, used in every message.
        lines: The file's lines, newline-stripped.
        front: The parsed frontmatter block.
        body_start: Index into ``lines`` of the first line after the block.
    """

    path: Path
    rel: str
    lines: list[str]
    front: Frontmatter
    body_start: int


class Report:
    """Findings accumulated across one run.

    Contract violations and ceiling warnings are collected rather than raised,
    so a run over a messy corpus reports everything wrong with it at once. That
    matters here specifically: the skill's rule is that it never refuses to
    work, so the checker must never stop at the first bad document either.
    """

    def __init__(self) -> None:
        self.errors: list[str] = []
        self.warnings: list[str] = []

    def error(self, message: str) -> None:
        """Record a contract violation. These set the exit status."""
        self.errors.append(message)

    def warn(self, message: str) -> None:
        """Record a ceiling breach or advisory. These never block."""
        self.warnings.append(message)

    @property
    def failed(self) -> bool:
        """Whether any contract violation was recorded."""
        return bool(self.errors)


# --------------------------------------------------------------------------
# frontmatter
# --------------------------------------------------------------------------


def strip_comment(value: str) -> str:
    """Drop a trailing ``#`` comment that is not inside quotes.

    Args:
        value: One raw frontmatter value, possibly with a trailing comment.

    Returns:
        The value with any unquoted trailing comment removed and whitespace
        stripped.
    """
    out: list[str] = []
    quote: str | None = None
    prev_space = True
    for char in value:
        if quote is not None:
            out.append(char)
            if char == quote:
                quote = None
        elif char in "\"'":
            quote = char
            out.append(char)
        elif char == "#" and prev_space:
            break
        else:
            out.append(char)
        prev_space = char.isspace()
    return "".join(out).strip()


def coerce_scalar(text: str) -> Scalar:
    """Turn already-comment-stripped text into a bool or a string.

    Only ``true`` and ``false`` become booleans. Everything else stays a
    string, with one layer of matched quotes removed. Numbers stay strings
    because no contract field is numeric.
    """
    if text in ("true", "false"):
        return text == "true"
    if len(text) >= 2 and text[0] == text[-1] and text[0] in "\"'":
        return text[1:-1]
    return text


def parse_value(raw: str) -> FrontValue:
    """Parse one ``key:`` value, which may be an inline list.

    Args:
        raw: Everything after the first colon on a frontmatter line.

    Returns:
        A scalar, or a flat list of scalars for ``[a, b]`` syntax. Nesting is
        not supported and is not attempted -- an inner bracket stays a string.
    """
    text = strip_comment(raw)
    if text.startswith("[") and text.endswith("]"):
        inner = text[1:-1].strip()
        if not inner:
            return []
        return [coerce_scalar(part.strip()) for part in inner.split(",")]
    return coerce_scalar(text)


def split_frontmatter(lines: list[str]) -> tuple[str, list[str], int]:
    """Locate the frontmatter block.

    Args:
        lines: The document's newline-stripped lines.

    Returns:
        ``(status, block_lines, body_start)`` where status is ``ok``,
        ``absent`` when the file does not open with ``---``, or
        ``unterminated`` when it opens one that never closes.
    """
    if not lines or lines[0].rstrip("\n") != "---":
        return "absent", [], 0
    for index in range(1, len(lines)):
        if lines[index].rstrip("\n") == "---":
            return "ok", lines[1:index], index + 1
    return "unterminated", [], 0


def parse_frontmatter(block: list[str]) -> tuple[Frontmatter, list[str]]:
    """Parse the restricted frontmatter subset, failing closed.

    Anything outside the contract's shapes -- a nested mapping, a multi-line
    scalar, an anchor -- is reported by line number rather than guessed at. A
    document with parse errors is still checked for everything else, so one
    stray line does not suppress the rest of its findings.

    Args:
        block: The lines between the two ``---`` markers.

    Returns:
        ``(fields, errors)``. The field map holds whatever parsed cleanly.
    """
    fields: Frontmatter = {}
    errors: list[str] = []
    pending: str | None = None
    for offset, raw in enumerate(block):
        lineno = offset + 2
        line = raw.rstrip("\n")
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        stripped = line.strip()
        if stripped.startswith("- "):
            if pending is None:
                errors.append(f"line {lineno}: list item with no key above it")
                continue
            bucket = fields[pending]
            if isinstance(bucket, list):
                bucket.append(coerce_scalar(strip_comment(stripped[2:])))
            continue
        if line[0].isspace():
            errors.append(f"line {lineno}: unsupported indented line {stripped!r}")
            pending = None
            continue
        if ":" not in line:
            errors.append(f"line {lineno}: not a `key: value` pair")
            pending = None
            continue
        name, _, rest = line.partition(":")
        name = name.strip()
        if strip_comment(rest) == "":
            fields[name] = []
            pending = name
        else:
            fields[name] = parse_value(rest)
            pending = None
    return fields, errors


# --------------------------------------------------------------------------
# document-level checks
# --------------------------------------------------------------------------


def check_fields(doc: Doc, report: Report) -> None:
    """Validate one document's frontmatter against the contract."""
    front = doc.front

    doc_type = front.get("type")
    if not isinstance(doc_type, str) or not doc_type:
        report.error(f"{doc.rel}: `type` is required and must be a name")

    lifecycle = front.get("lifecycle")
    if lifecycle not in LIFECYCLES:
        allowed = " | ".join(LIFECYCLES)
        report.error(f"{doc.rel}: `lifecycle` is required and must be one of {allowed}")

    owns = front.get("owns")
    if not isinstance(owns, list) or not owns:
        report.error(f"{doc.rel}: `owns` is required and needs >=1 claim")
    elif any(not isinstance(claim, str) or not claim for claim in owns):
        report.error(f"{doc.rel}: every `owns` entry must be a name")

    if "locked" in front and not isinstance(front["locked"], bool):
        report.error(f"{doc.rel}: `locked` must be true or false")

    handling = front.get("handling")
    if handling is not None and handling not in HANDLING_VALUES:
        allowed = " | ".join(HANDLING_VALUES)
        report.error(f"{doc.rel}: `handling` must be one of {allowed} when present")

    check_supersession(doc, report)

    for key in front:
        if key not in KNOWN_KEYS:
            report.warn(f"{doc.rel}: unknown frontmatter key `{key}`")


def check_supersession(doc: Doc, report: Report) -> None:
    """Check the supersession pointer and its optional back-link.

    A superseded document with no pointer tells the reader to look elsewhere
    without saying where, so the forward link is an error in both directions:
    missing when required, and present when not.
    """
    lifecycle = doc.front.get("lifecycle")
    link = doc.front.get("superseded-by")
    if lifecycle == "superseded":
        if not isinstance(link, str) or not link:
            report.error(f"{doc.rel}: `superseded-by` is required when lifecycle is superseded")
        elif not (doc.path.parent / link).exists():
            report.error(f"{doc.rel}: `superseded-by` target {link} not found")
    elif link is not None:
        report.error(f"{doc.rel}: `superseded-by` is only allowed on a superseded document")

    back = doc.front.get("supersedes")
    if back is None:
        return
    if not isinstance(back, list):
        report.error(f"{doc.rel}: `supersedes` must be a list")
        return
    for target in back:
        if not isinstance(target, str) or not (doc.path.parent / target).exists():
            report.warn(f"{doc.rel}: `supersedes` back-link {target} not found")


def find_sections(doc: Doc) -> list[tuple[str, int, int]]:
    """Return ``(heading, start_index, length_in_lines)`` per ``##`` section."""
    starts: list[tuple[str, int]] = []
    for index in range(doc.body_start, len(doc.lines)):
        line = doc.lines[index]
        if line.startswith("## "):
            starts.append((line[3:].strip(), index))
    sections: list[tuple[str, int, int]] = []
    for position, (heading, start) in enumerate(starts):
        following = starts[position + 1][1] if position + 1 < len(starts) else None
        end = following if following is not None else len(doc.lines)
        sections.append((heading, start, end - start))
    return sections


def name_longest(sections: list[tuple[str, int, int]], limit: int = 3) -> str:
    """Name the sections a split plan should extract, longest first.

    A document-level warning that delegates the naming back to the reader is
    noise: the per-section lengths were already computed to produce it, so it
    can say what to extract rather than asking.
    """
    ranked = sorted(sections, key=lambda section: section[2], reverse=True)
    named = [f"'{heading}' ({length})" for heading, _, length in ranked[:limit]]
    return ", ".join(named) if named else "its longest sections"


def check_length(doc: Doc, report: Report) -> None:
    """Warn on section and document ceilings, always naming a remedy.

    A warning that leaves the reader to find the remedy is noise, so every
    message here names the section to extract or the plan to propose.
    """
    sections = find_sections(doc)
    # A document whose whole body is one section is the expected shape of a
    # fresh fork, and telling it to fork that section into its own document
    # tells it to fork itself. The document ceilings below still cover it.
    if len(sections) > 1:
        for heading, _, length in sections:
            if length > SECTION_WARN_LINES:
                report.warn(
                    f"{doc.rel}: section '{heading}' is {length} lines; "
                    f"propose forking it into its own document"
                )
    total = len(doc.lines)
    if total > DOC_LIMIT_LINES:
        report.warn(
            f"{doc.rel}: {total} lines, past the {DOC_LIMIT_LINES}-line "
            f"limit; propose a split plan extracting {name_longest(sections)}"
        )
    elif total > DOC_WARN_LINES:
        report.warn(
            f"{doc.rel}: {total} lines, past the {DOC_WARN_LINES}-line "
            f"backstop; propose extracting {name_longest(sections)}"
        )


def locate_amendments(doc: Doc) -> tuple[int | None, int]:
    """Find the ``## Amendments`` section.

    Returns:
        ``(start_index, end_index)``, with a ``None`` start when the section is
        absent. The end is exclusive and defaults to end-of-file.
    """
    start: int | None = None
    for index in range(doc.body_start, len(doc.lines)):
        line = doc.lines[index]
        if start is None:
            if line.strip() == "## Amendments":
                start = index
        elif line.startswith("## "):
            return start, index
    return start, len(doc.lines)


def check_amendments(doc: Doc, report: Report) -> None:
    """Pair every amendment entry with at least one inline marker.

    An amendment nobody finds is worse than none, because the document then
    looks maintained while the stale sentence carries no signal. One correction
    routinely invalidates more than one point, so the rule is a marker at every
    point it invalidates rather than exactly one per entry. Zero markers, and a
    marker with no entry, are both errors.
    """
    start, end = locate_amendments(doc)
    if start is None:
        entries: list[str] = []
        body = range(doc.body_start, len(doc.lines))
    else:
        entries = [
            match.group(1)
            for index in range(start, end)
            if (match := AMENDMENT_ENTRY.match(doc.lines[index]))
        ]
        body = range(doc.body_start, start)

    markers: list[str] = []
    for index in body:
        markers.extend(AMENDMENT_MARKER.findall(doc.lines[index]))

    for number in entries:
        if markers.count(number) == 0:
            report.error(
                f"{doc.rel}: amendment A{number} has no inline marker in the "
                f"body; mark every point it invalidates with "
                f"`[amended A{number}]`"
            )
    for number in sorted(set(markers) - set(entries)):
        report.error(
            f"{doc.rel}: inline marker [amended A{number}] has no matching "
            f"`### A{number}` entry under ## Amendments"
        )

    if len(entries) >= AMENDMENT_WARN_COUNT:
        report.warn(
            f"{doc.rel}: {len(entries)} amendments; propose superseding it "
            f"with a named successor document"
        )


# --------------------------------------------------------------------------
# corpus-level checks and the index
# --------------------------------------------------------------------------


def claims_of(doc: Doc) -> list[str]:
    """Return the document's well-formed ownership claims."""
    owns = doc.front.get("owns")
    if not isinstance(owns, list):
        return []
    return [claim for claim in owns if isinstance(claim, str) and claim]


def check_ownership(docs: list[Doc], report: Report) -> None:
    """No topic may be claimed by two documents.

    This is the root-cause check. Two documents disagreeing is a symptom of
    neither having declared what it owns, so a duplicate claim is an error
    rather than a warning.
    """
    claimed: dict[str, list[str]] = {}
    for doc in docs:
        for claim in claims_of(doc):
            claimed.setdefault(claim, []).append(doc.rel)
    for claim, holders in sorted(claimed.items()):
        if len(holders) > 1:
            report.error(f"ownership collision on '{claim}': claimed by {', '.join(holders)}")


def render_index(docs: list[Doc]) -> str:
    """Build the index from the ownership declarations, never by hand.

    The handling column appears only when at least one document declares one,
    so a corpus with no restricted material does not carry a column of dashes.
    """
    show_handling = any(doc.front.get("handling") is not None for doc in docs)
    rows: list[list[str]] = []
    for doc in docs:
        doc_type = doc.front.get("type")
        lifecycle = doc.front.get("lifecycle")
        handling = doc.front.get("handling")
        tail = [
            doc_type if isinstance(doc_type, str) else "?",
            lifecycle if isinstance(lifecycle, str) else "?",
            "yes" if doc.front.get("locked") is True else "no",
        ]
        if show_handling:
            tail.append(handling if isinstance(handling, str) else "-")
        for claim in claims_of(doc):
            rows.append([claim, doc.rel, *tail])
    rows.sort()
    headers = ["Owns", "Document", "Type", "Lifecycle", "Locked"]
    if show_handling:
        headers.append("Handling")
    lines = [
        INDEX_MARKER,
        "",
        "# Document index",
        "",
        "| " + " | ".join(headers) + " |",
        "|" + "---|" * len(headers),
    ]
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    lines.append("")
    return "\n".join(lines)


def write_index(path: Path, content: str, report: Report) -> None:
    """Write the generated index, refusing to clobber a hand-written file.

    An index file without the generated marker was written by a human, and
    silently replacing it would destroy work while reporting success.
    """
    if path.exists():
        try:
            existing = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError) as exc:
            report.error(f"{path}: cannot read existing index ({exc})")
            return
        head = existing.lstrip().splitlines()
        if not head or head[0].strip() != INDEX_MARKER:
            report.error(
                f"{path}: exists without the generated-index marker; refusing "
                f"to overwrite a hand-written file"
            )
            return
    try:
        path.write_text(content, encoding="utf-8")
    except OSError as exc:
        report.error(f"{path}: cannot write index ({exc})")


def compare_index(path: Path, content: str, report: Report) -> None:
    """Compare the generated index to the file on disk, never writing.

    A read-only gate wants exactly this. Regenerating in place would make the
    gate the thing that silently fixes the drift it exists to report, which
    turns a failing check into a dirty working tree and nothing else.
    """
    if not path.exists():
        report.error(f"{path}: index missing; generate it with --index")
        return
    try:
        existing = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        report.error(f"{path}: cannot read index ({exc})")
        return
    if existing == content:
        return
    drift = [
        line
        for line in difflib.unified_diff(
            existing.splitlines(), content.splitlines(), lineterm="", n=0
        )
        if line[:1] in "+-" and not line.startswith(("---", "+++"))
    ]
    shown = drift[:INDEX_DRIFT_MAX]
    detail = "; ".join(shown)
    if len(drift) > len(shown):
        detail += f"; and {len(drift) - len(shown)} more"
    report.error(f"{path}: index is stale ({detail}); regenerate it with --index")


# --------------------------------------------------------------------------
# fork verification
# --------------------------------------------------------------------------


def git_show(rev: str, path: Path) -> tuple[str | None, str | None]:
    """Read a file as of ``rev``, returning ``(text, problem)``.

    Git is the only external dependency in this script and it is reachable
    only from here. Its absence is reported and the check is skipped, never
    silently passed -- a verification that quietly does nothing is worse than
    one that is not run at all.
    """
    if shutil.which("git") is None:
        return None, "git is not on PATH; the fork check was SKIPPED, not passed"
    try:
        proc = subprocess.run(  # noqa: S603
            ["git", "show", f"{rev}:./{path.name}"],
            cwd=path.parent if str(path.parent) else ".",
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError as exc:
        return None, f"cannot run git ({exc})"
    if proc.returncode != 0:
        return None, f"git show {rev}:{path} failed: {proc.stderr.strip()}"
    return proc.stdout, None


def parent_is_dirty(parent: Path) -> bool:
    """Whether ``parent`` has uncommitted changes.

    A fork is normally performed in the document you were just editing, so the
    parent is usually dirty and ``--since HEAD`` then compares the child against
    a version that predates the session. That produces a mismatch on a correct
    relocation, which reads as a botched fork. Knowing this lets the mismatch
    explain itself; it is never a failure on its own, because a parent whose
    edits fell outside the moved section compares perfectly well.
    """
    if shutil.which("git") is None:
        return False
    try:
        proc = subprocess.run(  # noqa: S603
            ["git", "status", "--porcelain", "--", parent.name],
            cwd=parent.parent if str(parent.parent) else ".",
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError:
        return False
    return proc.returncode == 0 and bool(proc.stdout.strip())


def extract_section(lines: list[str], heading: str) -> list[str] | None:
    """Return the named ``##`` section including its heading, or None.

    A deeper heading does not end the section: ``### Foo`` is content inside
    it, and treating it as a boundary would silently compare a fragment and
    call the fork verified.
    """
    want = heading.strip()
    start: int | None = None
    for index, line in enumerate(lines):
        if start is None:
            if line.strip() == want:
                start = index
        elif line.startswith("## "):
            return lines[start:index]
    return None if start is None else lines[start:]


def trim_blanks(lines: list[str]) -> list[str]:
    """Drop leading and trailing blank lines.

    Hygiene hooks trim trailing whitespace and fix end-of-file newlines after
    a fork has already moved the text, and a section relocated to the end of a
    file predictably loses the blank that separated it from the next heading.
    Those are formatter artifacts. A changed word is not, and still fails.
    """
    start = 0
    end = len(lines)
    while start < end and not lines[start].strip():
        start += 1
    while end > start and not lines[end - 1].strip():
        end -= 1
    return lines[start:end]


MARKDOWN_LINK = re.compile(r"\[[^\]]*\]\(([^)]+)\)")


def section_is_fork_pointer(section: list[str], child: Path) -> bool:
    """Whether ``section`` is the pointer a completed fork leaves behind.

    The second wrong-baseline case. Running the check *after* committing the
    fork reads a parent whose section is already the retained heading plus a
    pointer, so the comparison is against the wrong revision again -- and the
    parent is clean, so the dirty-tree hint correctly stays quiet.

    The test requires the body to be nothing but a blockquote *and* to link to
    the child being compared. Both together make it conclusive rather than
    likely: a section that quotes a specification is all-blockquote too, and
    would otherwise be accused of being a pointer.
    """
    body = trim_blanks(section[1:])
    if not body:
        return False
    if any(line.strip() and not line.lstrip().startswith(">") for line in body):
        return False
    targets = {Path(target).name for line in body for target in MARKDOWN_LINK.findall(line)}
    return child.name in targets


def verify_fork(spec: str, child: Path, rev: str, report: Report) -> bool:
    """Check that a forked section arrived byte-identical.

    Args:
        spec: ``PARENT.md:## Section`` -- the source file and the heading that
            moved out of it.
        child: The document the section moved into.
        rev: The revision to read the parent at, before the fork.
        report: Collector for every problem found.

    Returns:
        Whether the relocation verified. Reading a ``git diff`` by eye does not
        work for the sequence conversion prescribes: the child is untracked,
        the parent's diff also carries the frontmatter the previous step added,
        and the retained heading is coalesced as context. All three read as a
        mismatch on a correct fork, which is why this exists.
    """
    parent_raw, sep, heading = spec.partition(":")
    if not sep or not heading.strip() or not parent_raw:
        report.error(f"--verify-fork needs PARENT.md:'## Section'; got {spec!r}")
        return False
    parent = Path(parent_raw)
    dirty = parent_is_dirty(parent)
    already_forked = False

    def baseline_hint() -> None:
        """Explain a failure that the comparison baseline, not the fork, caused.

        Two causes, and the more specific one wins: a parent already carrying
        the pointer is conclusive, where a dirty parent is only likely.
        """
        if already_forked:
            report.warn(
                f"{parent} at {rev} already carries the fork pointer to {child.name}, so "
                f"the section had moved out of it by that revision and there was nothing "
                f"left to compare against. Pass --since a revision from BEFORE the fork."
            )
        elif dirty:
            report.warn(
                f"{parent} has uncommitted changes, so --since {rev} compared the child "
                f"against the COMMITTED version, not the one the section was forked out "
                f"of. Commit the parent's pre-fork state and re-run, or pass --since with "
                f"a revision that has it."
            )

    text, problem = git_show(rev, parent)
    if text is None:
        report.error(problem or f"cannot read {parent} at {rev}")
        baseline_hint()
        return False
    section = extract_section(text.splitlines(), heading)
    if section is None:
        report.error(f"{parent} at {rev}: no section {heading.strip()!r}")
        baseline_hint()
        return False
    already_forked = section_is_fork_pointer(section, child)
    try:
        child_lines = child.read_text(encoding="utf-8").splitlines()
    except (OSError, UnicodeDecodeError) as exc:
        report.error(f"{child}: cannot read ({exc})")
        baseline_hint()
        return False
    _, _, body_start = split_frontmatter(child_lines)
    want = trim_blanks(section)
    have = trim_blanks(child_lines[body_start:])
    for number, (left, right) in enumerate(zip(want, have, strict=False), start=1):
        if left != right:
            report.error(
                f"fork mismatch at body line {number}: {parent} has {left!r}, {child} has {right!r}"
            )
            baseline_hint()
            return False
    if len(want) != len(have):
        report.error(
            f"fork mismatch: the section in {parent} is {len(want)} lines, "
            f"the body of {child} is {len(have)}"
        )
        baseline_hint()
        return False
    print(f"fork verified: {len(want)} lines identical")
    return True


# --------------------------------------------------------------------------
# driver
# --------------------------------------------------------------------------


def collect(root: Path, skip: Path | None) -> list[Path]:
    """Return every markdown file under ``root``, minus the named index."""
    found: list[Path] = []
    for path in sorted(root.rglob("*.md")):
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        if skip is not None and path.resolve() == skip:
            continue
        found.append(path)
    return found


def is_generated_index(lines: list[str]) -> bool:
    """Whether the file's first non-blank line is the generated-index marker.

    Recognised by identity rather than by path: a generated index is a
    corpus-shaped markdown file that legitimately carries no frontmatter, and
    ``--index`` may name a different location than the one already on disk.
    """
    for line in lines:
        if line.strip():
            return line.strip() == INDEX_MARKER
    return False


def load(path: Path, root: Path, report: Report, survey: bool = False) -> Doc | None:
    """Read and parse one document.

    Args:
        path: The file to read.
        root: The corpus root, for relative naming in messages.
        report: Collector for anything the contract forbids.
        survey: When true, a missing or malformed frontmatter block is not an
            error and the document is still returned for structural analysis.
            A pre-conversion corpus has no frontmatter by definition, so
            refusing to look at it would make the survey useless exactly where
            it is needed.

    Returns:
        The parsed document, or ``None`` when it is a generated index or could
        not be read. An unreadable file is reported and skipped rather than
        aborting the run.
    """
    rel = str(path.relative_to(root))
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        report.error(f"{rel}: cannot read ({exc})")
        return None
    lines = text.splitlines()
    if is_generated_index(lines):
        return None
    status, block, body_start = split_frontmatter(lines)
    if status != "ok":
        if not survey:
            detail = (
                "no frontmatter block"
                if status == "absent"
                else "frontmatter opened but never closed"
            )
            report.error(f"{rel}: {detail}")
            return None
        return Doc(path=path, rel=rel, lines=lines, front={}, body_start=0)
    front, parse_errors = parse_frontmatter(block)
    if not survey:
        for message in parse_errors:
            report.error(f"{rel}: {message}")
    return Doc(path=path, rel=rel, lines=lines, front=front, body_start=body_start)


def render_survey(docs: list[Doc]) -> str:
    """Render the pre-conversion inventory that conversion Phase 1 needs.

    Structure only -- line counts, sections, and which sections are fork
    candidates. Implicit ownership and lifecycle live in prose and are the
    reader's job, not this script's.
    """
    lines: list[str] = []
    for doc in sorted(docs, key=lambda d: d.rel):
        state = "frontmatter present" if doc.front else "no frontmatter"
        sections = find_sections(doc)
        lines.append(f"{doc.rel} -- {len(doc.lines)} lines, {state}, {len(sections)} sections")
        for heading, _, length in sections:
            flag = "FORK" if length > SECTION_WARN_LINES else "    "
            lines.append(f"  {flag}  {length:>5}  {heading}")
        lines.append("")
    return "\n".join(lines)


def usage_error(
    root: Path | None,
    index: Path | None,
    check_index: Path | None,
    survey: bool,
) -> str | None:
    """Return a usage-error message, or None when the arguments are usable.

    Validated before any file is read, so a mistyped path fails immediately
    rather than after a full corpus walk.
    """
    if root is None:
        return "a corpus directory is required unless --verify-fork is used"
    if not root.is_dir():
        return f"{root} is not a directory"
    if index is not None and not index.parent.is_dir():
        return f"--index directory {index.parent} does not exist"
    if index is not None and check_index is not None:
        return "--index writes and --check-index compares; use one"
    if survey and index is not None:
        return "--survey does not write an index"
    if survey and check_index is not None:
        return "--survey does not check an index"
    return None


def run_contract_checks(
    docs: list[Doc],
    report: Report,
    index: Path | None,
    check_index: Path | None = None,
) -> None:
    """Run every contract check over the corpus and handle the index."""
    for doc in docs:
        check_fields(doc, report)
        check_length(doc, report)
        check_amendments(doc, report)
    check_ownership(docs, report)
    # Only nag about a missing index when neither index flag was given. A
    # read-only gate passes --check-index precisely so it does not write, and
    # warning it for not writing teaches the reader to skim the real findings.
    if len(docs) >= 2 and index is None and check_index is None:
        report.warn("corpus has 2+ documents and no index was generated; re-run with --index")
    if index is not None:
        write_index(index, render_index(docs), report)
    if check_index is not None:
        compare_index(check_index, render_index(docs), report)


def emit(report: Report, count: int, quiet: bool, survey: bool) -> int:
    """Print the findings and return the process exit status."""
    for message in report.errors:
        print(f"ERROR {message}")
    if not quiet:
        for message in report.warnings:
            print(f"WARN  {message}")
    if survey:
        print(f"{count} document(s) surveyed")
    else:
        print(
            f"\n{count} document(s), {len(report.errors)} error(s), "
            f"{len(report.warnings)} warning(s)"
        )
    return EXIT_CONTRACT_ERRORS if report.failed else EXIT_OK


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(
        description="Validate a design-forge corpus and regenerate its index."
    )
    parser.add_argument(
        "root",
        type=Path,
        nargs="?",
        default=None,
        help="directory holding the corpus (omit only with --verify-fork)",
    )
    parser.add_argument(
        "--index",
        type=Path,
        default=None,
        help="path to write the generated index to (omit to skip generation)",
    )
    parser.add_argument(
        "--check-index",
        type=Path,
        default=None,
        dest="check_index",
        help=(
            "compare the generated index to this file without writing it; "
            "exit 1 on drift. What a read-only gate wants"
        ),
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="report errors only, suppress warnings",
    )
    parser.add_argument(
        "--survey",
        action="store_true",
        help=(
            "pre-conversion inventory: report structure and ceilings only, "
            "treating absent frontmatter as expected rather than as an error"
        ),
    )
    parser.add_argument(
        "--verify-fork",
        nargs=2,
        metavar=("PARENT.md:## SECTION", "CHILD.md"),
        default=None,
        dest="verify_fork",
        help=(
            "check that a forked section arrived byte-identical, comparing "
            "the child's body to the section as it was at --since"
        ),
    )
    parser.add_argument(
        "--since",
        default="HEAD",
        help="revision to read the parent at for --verify-fork (default HEAD)",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    """Run the checker.

    Returns:
        ``0`` when no contract error was found, including when only warnings
        were, because ceilings never block. ``1`` on contract errors. ``2`` on
        a usage problem, which is the caller's fault rather than the corpus's.
    """
    args = build_parser().parse_args(argv)
    root: Path | None = args.root
    index: Path | None = args.index
    check_index: Path | None = args.check_index

    if args.verify_fork is not None:
        spec, child = args.verify_fork
        report = Report()
        verify_fork(spec, Path(child), args.since, report)
        for message in report.errors:
            print(f"ERROR {message}")
        # Warnings carry the baseline hints, and a mismatch without its cause is
        # the confusing report they exist to replace. This branch printed errors
        # only until 2026-08-24, so both hints were reachable from the unit tests
        # and invisible from the command line.
        if not args.quiet:
            for message in report.warnings:
                print(f"WARN  {message}")
        return EXIT_CONTRACT_ERRORS if report.failed else EXIT_OK

    problem = usage_error(root, index, check_index, args.survey)
    if problem is not None:
        print(f"error: {problem}", file=sys.stderr)
        return EXIT_BAD_USAGE
    assert root is not None  # noqa: S101 -- usage_error above guarantees it

    report = Report()
    named_index = index if index is not None else check_index
    skip = named_index.resolve() if named_index is not None else None
    docs = [
        doc
        for path in collect(root, skip)
        if (doc := load(path, root, report, survey=args.survey)) is not None
    ]

    if args.survey:
        print(render_survey(docs))
    else:
        run_contract_checks(docs, report, index, check_index)

    return emit(report, len(docs), quiet=args.quiet, survey=args.survey)


if __name__ == "__main__":
    raise SystemExit(main())
