#!/usr/bin/env python3
"""Validate a design-forge corpus and regenerate its index.

Standard library only, and deliberately so: a skill runs on machines nobody
configured for it, so this must not need pyyaml, uv, or a virtualenv. The
frontmatter parser below understands exactly the shapes the contract defines --
scalars, booleans, and flat lists of them -- and fails closed by naming the file
and line when it meets anything else. It is not a YAML implementation and MUST
NOT grow into one.

Line length is 88 rather than the 120 the house Python style prefers, because
pre-commit runs ruff with its defaults over `skills/` and repo-local hygiene
wins. NamedTuple rather than attrs or dataclasses, because attrs would be a
runtime dependency this script cannot assume.

Nothing here raises on corpus content. Every problem is accumulated and reported
at once, so one malformed document does not hide the other nine. Exit status is
1 on contract errors and 0 on warnings, because length ceilings warn and propose
but never block.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import NamedTuple

#: A frontmatter leaf value, after the restricted parse.
Scalar = str | bool
#: A frontmatter field value: a leaf, or a flat list of them.
FrontValue = Scalar | list[Scalar]
#: One document's parsed frontmatter block.
Frontmatter = dict[str, FrontValue]

LIFECYCLES = ("draft", "active", "stale", "superseded")
KNOWN_KEYS = (
    "type",
    "lifecycle",
    "owns",
    "locked",
    "superseded-by",
    "supersedes",
    "handling",
)
# Fixed, unlike `type`. The whole point of the field is to be a signal, and a
# freeform value means a typo silently disables it. Spelling is all this script
# can check -- nothing here enforces the restriction itself.
HANDLING_VALUES = ("internal", "customer-confidential", "third-party")
SECTION_WARN_LINES = 200
DOC_WARN_LINES = 1000
DOC_LIMIT_LINES = 2000
AMENDMENT_WARN_COUNT = 5

INDEX_MARKER = "<!-- generated by design-forge check_corpus.py; do not edit -->"
AMENDMENT_ENTRY = re.compile(r"^###\s+A(\d+)\b")
AMENDMENT_MARKER = re.compile(r"\[amended A(\d+)\]")
SKIP_DIRS = frozenset({".git", ".venv", "node_modules", "__pycache__"})

EXIT_OK = 0
EXIT_CONTRACT_ERRORS = 1
EXIT_BAD_USAGE = 2


class Doc(NamedTuple):
    """One parsed corpus document.

    Attributes:
        path: Absolute or invocation-relative path to the file.
        rel: Path relative to the corpus root, used in every message.
        lines: The file's lines, newline-stripped.
        front: The parsed frontmatter block.
        body_start: Index into ``lines`` of the first line after the block.
    """

    path: Path
    rel: str
    lines: list[str]
    front: Frontmatter
    body_start: int


class Report:
    """Findings accumulated across one run.

    Contract violations and ceiling warnings are collected rather than raised,
    so a run over a messy corpus reports everything wrong with it at once. That
    matters here specifically: the skill's rule is that it never refuses to
    work, so the checker must never stop at the first bad document either.
    """

    def __init__(self) -> None:
        self.errors: list[str] = []
        self.warnings: list[str] = []

    def error(self, message: str) -> None:
        """Record a contract violation. These set the exit status."""
        self.errors.append(message)

    def warn(self, message: str) -> None:
        """Record a ceiling breach or advisory. These never block."""
        self.warnings.append(message)

    @property
    def failed(self) -> bool:
        """Whether any contract violation was recorded."""
        return bool(self.errors)


# --------------------------------------------------------------------------
# frontmatter
# --------------------------------------------------------------------------


def strip_comment(value: str) -> str:
    """Drop a trailing ``#`` comment that is not inside quotes.

    Args:
        value: One raw frontmatter value, possibly with a trailing comment.

    Returns:
        The value with any unquoted trailing comment removed and whitespace
        stripped.
    """
    out: list[str] = []
    quote: str | None = None
    prev_space = True
    for char in value:
        if quote is not None:
            out.append(char)
            if char == quote:
                quote = None
        elif char in "\"'":
            quote = char
            out.append(char)
        elif char == "#" and prev_space:
            break
        else:
            out.append(char)
        prev_space = char.isspace()
    return "".join(out).strip()


def coerce_scalar(text: str) -> Scalar:
    """Turn already-comment-stripped text into a bool or a string.

    Only ``true`` and ``false`` become booleans. Everything else stays a
    string, with one layer of matched quotes removed. Numbers stay strings
    because no contract field is numeric.
    """
    if text in ("true", "false"):
        return text == "true"
    if len(text) >= 2 and text[0] == text[-1] and text[0] in "\"'":
        return text[1:-1]
    return text


def parse_value(raw: str) -> FrontValue:
    """Parse one ``key:`` value, which may be an inline list.

    Args:
        raw: Everything after the first colon on a frontmatter line.

    Returns:
        A scalar, or a flat list of scalars for ``[a, b]`` syntax. Nesting is
        not supported and is not attempted -- an inner bracket stays a string.
    """
    text = strip_comment(raw)
    if text.startswith("[") and text.endswith("]"):
        inner = text[1:-1].strip()
        if not inner:
            return []
        return [coerce_scalar(part.strip()) for part in inner.split(",")]
    return coerce_scalar(text)


def split_frontmatter(lines: list[str]) -> tuple[str, list[str], int]:
    """Locate the frontmatter block.

    Args:
        lines: The document's newline-stripped lines.

    Returns:
        ``(status, block_lines, body_start)`` where status is ``ok``,
        ``absent`` when the file does not open with ``---``, or
        ``unterminated`` when it opens one that never closes.
    """
    if not lines or lines[0].rstrip("\n") != "---":
        return "absent", [], 0
    for index in range(1, len(lines)):
        if lines[index].rstrip("\n") == "---":
            return "ok", lines[1:index], index + 1
    return "unterminated", [], 0


def parse_frontmatter(block: list[str]) -> tuple[Frontmatter, list[str]]:
    """Parse the restricted frontmatter subset, failing closed.

    Anything outside the contract's shapes -- a nested mapping, a multi-line
    scalar, an anchor -- is reported by line number rather than guessed at. A
    document with parse errors is still checked for everything else, so one
    stray line does not suppress the rest of its findings.

    Args:
        block: The lines between the two ``---`` markers.

    Returns:
        ``(fields, errors)``. The field map holds whatever parsed cleanly.
    """
    fields: Frontmatter = {}
    errors: list[str] = []
    pending: str | None = None
    for offset, raw in enumerate(block):
        lineno = offset + 2
        line = raw.rstrip("\n")
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        stripped = line.strip()
        if stripped.startswith("- "):
            if pending is None:
                errors.append(f"line {lineno}: list item with no key above it")
                continue
            bucket = fields[pending]
            if isinstance(bucket, list):
                bucket.append(coerce_scalar(strip_comment(stripped[2:])))
            continue
        if line[0].isspace():
            errors.append(f"line {lineno}: unsupported indented line {stripped!r}")
            pending = None
            continue
        if ":" not in line:
            errors.append(f"line {lineno}: not a `key: value` pair")
            pending = None
            continue
        name, _, rest = line.partition(":")
        name = name.strip()
        if strip_comment(rest) == "":
            fields[name] = []
            pending = name
        else:
            fields[name] = parse_value(rest)
            pending = None
    return fields, errors


# --------------------------------------------------------------------------
# document-level checks
# --------------------------------------------------------------------------


def check_fields(doc: Doc, report: Report) -> None:
    """Validate one document's frontmatter against the contract."""
    front = doc.front

    doc_type = front.get("type")
    if not isinstance(doc_type, str) or not doc_type:
        report.error(f"{doc.rel}: `type` is required and must be a name")

    lifecycle = front.get("lifecycle")
    if lifecycle not in LIFECYCLES:
        allowed = " | ".join(LIFECYCLES)
        report.error(f"{doc.rel}: `lifecycle` is required and must be one of {allowed}")

    owns = front.get("owns")
    if not isinstance(owns, list) or not owns:
        report.error(f"{doc.rel}: `owns` is required and needs >=1 claim")
    elif any(not isinstance(claim, str) or not claim for claim in owns):
        report.error(f"{doc.rel}: every `owns` entry must be a name")

    if "locked" in front and not isinstance(front["locked"], bool):
        report.error(f"{doc.rel}: `locked` must be true or false")

    handling = front.get("handling")
    if handling is not None and handling not in HANDLING_VALUES:
        allowed = " | ".join(HANDLING_VALUES)
        report.error(f"{doc.rel}: `handling` must be one of {allowed} when present")

    check_supersession(doc, report)

    for key in front:
        if key not in KNOWN_KEYS:
            report.warn(f"{doc.rel}: unknown frontmatter key `{key}`")


def check_supersession(doc: Doc, report: Report) -> None:
    """Check the supersession pointer and its optional back-link.

    A superseded document with no pointer tells the reader to look elsewhere
    without saying where, so the forward link is an error in both directions:
    missing when required, and present when not.
    """
    lifecycle = doc.front.get("lifecycle")
    link = doc.front.get("superseded-by")
    if lifecycle == "superseded":
        if not isinstance(link, str) or not link:
            report.error(
                f"{doc.rel}: `superseded-by` is required when lifecycle is superseded"
            )
        elif not (doc.path.parent / link).exists():
            report.error(f"{doc.rel}: `superseded-by` target {link} not found")
    elif link is not None:
        report.error(
            f"{doc.rel}: `superseded-by` is only allowed on a superseded document"
        )

    back = doc.front.get("supersedes")
    if back is None:
        return
    if not isinstance(back, list):
        report.error(f"{doc.rel}: `supersedes` must be a list")
        return
    for target in back:
        if not isinstance(target, str) or not (doc.path.parent / target).exists():
            report.warn(f"{doc.rel}: `supersedes` back-link {target} not found")


def find_sections(doc: Doc) -> list[tuple[str, int, int]]:
    """Return ``(heading, start_index, length_in_lines)`` per ``##`` section."""
    starts: list[tuple[str, int]] = []
    for index in range(doc.body_start, len(doc.lines)):
        line = doc.lines[index]
        if line.startswith("## "):
            starts.append((line[3:].strip(), index))
    sections: list[tuple[str, int, int]] = []
    for position, (heading, start) in enumerate(starts):
        following = starts[position + 1][1] if position + 1 < len(starts) else None
        end = following if following is not None else len(doc.lines)
        sections.append((heading, start, end - start))
    return sections


def check_length(doc: Doc, report: Report) -> None:
    """Warn on section and document ceilings, always naming a remedy.

    A warning that leaves the reader to find the remedy is noise, so every
    message here names the section to extract or the plan to propose.
    """
    for heading, _, length in find_sections(doc):
        if length > SECTION_WARN_LINES:
            report.warn(
                f"{doc.rel}: section '{heading}' is {length} lines; propose "
                f"forking it into its own document"
            )
    total = len(doc.lines)
    if total > DOC_LIMIT_LINES:
        report.warn(
            f"{doc.rel}: {total} lines, past the {DOC_LIMIT_LINES}-line limit; "
            f"propose a split plan naming each section to extract"
        )
    elif total > DOC_WARN_LINES:
        report.warn(
            f"{doc.rel}: {total} lines, past the {DOC_WARN_LINES}-line "
            f"backstop; propose extracting its longest sections"
        )


def locate_amendments(doc: Doc) -> tuple[int | None, int]:
    """Find the ``## Amendments`` section.

    Returns:
        ``(start_index, end_index)``, with a ``None`` start when the section is
        absent. The end is exclusive and defaults to end-of-file.
    """
    start: int | None = None
    for index in range(doc.body_start, len(doc.lines)):
        line = doc.lines[index]
        if start is None:
            if line.strip() == "## Amendments":
                start = index
        elif line.startswith("## "):
            return start, index
    return start, len(doc.lines)


def check_amendments(doc: Doc, report: Report) -> None:
    """Pair every amendment entry with exactly one inline marker.

    An amendment nobody finds is worse than none, because the document then
    looks maintained while the stale sentence carries no signal. Both halves of
    the pairing are therefore errors, in both directions.
    """
    start, end = locate_amendments(doc)
    if start is None:
        entries: list[str] = []
        body = range(doc.body_start, len(doc.lines))
    else:
        entries = [
            match.group(1)
            for index in range(start, end)
            if (match := AMENDMENT_ENTRY.match(doc.lines[index]))
        ]
        body = range(doc.body_start, start)

    markers: list[str] = []
    for index in body:
        markers.extend(AMENDMENT_MARKER.findall(doc.lines[index]))

    for number in entries:
        hits = markers.count(number)
        if hits != 1:
            report.error(
                f"{doc.rel}: amendment A{number} has {hits} inline markers in "
                f"the body; exactly one `[amended A{number}]` is required"
            )
    for number in sorted(set(markers) - set(entries)):
        report.error(
            f"{doc.rel}: inline marker [amended A{number}] has no matching "
            f"`### A{number}` entry under ## Amendments"
        )

    if len(entries) >= AMENDMENT_WARN_COUNT:
        report.warn(
            f"{doc.rel}: {len(entries)} amendments; propose superseding it "
            f"with a named successor document"
        )


# --------------------------------------------------------------------------
# corpus-level checks and the index
# --------------------------------------------------------------------------


def claims_of(doc: Doc) -> list[str]:
    """Return the document's well-formed ownership claims."""
    owns = doc.front.get("owns")
    if not isinstance(owns, list):
        return []
    return [claim for claim in owns if isinstance(claim, str) and claim]


def check_ownership(docs: list[Doc], report: Report) -> None:
    """No topic may be claimed by two documents.

    This is the root-cause check. Two documents disagreeing is a symptom of
    neither having declared what it owns, so a duplicate claim is an error
    rather than a warning.
    """
    claimed: dict[str, list[str]] = {}
    for doc in docs:
        for claim in claims_of(doc):
            claimed.setdefault(claim, []).append(doc.rel)
    for claim, holders in sorted(claimed.items()):
        if len(holders) > 1:
            report.error(
                f"ownership collision on '{claim}': claimed by {', '.join(holders)}"
            )


def render_index(docs: list[Doc]) -> str:
    """Build the index from the ownership declarations, never by hand.

    The handling column appears only when at least one document declares one,
    so a corpus with no restricted material does not carry a column of dashes.
    """
    show_handling = any(doc.front.get("handling") is not None for doc in docs)
    rows: list[list[str]] = []
    for doc in docs:
        doc_type = doc.front.get("type")
        lifecycle = doc.front.get("lifecycle")
        handling = doc.front.get("handling")
        tail = [
            doc_type if isinstance(doc_type, str) else "?",
            lifecycle if isinstance(lifecycle, str) else "?",
            "yes" if doc.front.get("locked") is True else "no",
        ]
        if show_handling:
            tail.append(handling if isinstance(handling, str) else "-")
        for claim in claims_of(doc):
            rows.append([claim, doc.rel, *tail])
    rows.sort()
    headers = ["Owns", "Document", "Type", "Lifecycle", "Locked"]
    if show_handling:
        headers.append("Handling")
    lines = [
        INDEX_MARKER,
        "",
        "# Document index",
        "",
        "| " + " | ".join(headers) + " |",
        "|" + "---|" * len(headers),
    ]
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    lines.append("")
    return "\n".join(lines)


def write_index(path: Path, content: str, report: Report) -> None:
    """Write the generated index, refusing to clobber a hand-written file.

    An index file without the generated marker was written by a human, and
    silently replacing it would destroy work while reporting success.
    """
    if path.exists():
        try:
            existing = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError) as exc:
            report.error(f"{path}: cannot read existing index ({exc})")
            return
        head = existing.lstrip().splitlines()
        if not head or head[0].strip() != INDEX_MARKER:
            report.error(
                f"{path}: exists without the generated-index marker; refusing "
                f"to overwrite a hand-written file"
            )
            return
    try:
        path.write_text(content, encoding="utf-8")
    except OSError as exc:
        report.error(f"{path}: cannot write index ({exc})")


# --------------------------------------------------------------------------
# driver
# --------------------------------------------------------------------------


def collect(root: Path, skip: Path | None) -> list[Path]:
    """Return every markdown file under ``root``, minus the named index."""
    found: list[Path] = []
    for path in sorted(root.rglob("*.md")):
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        if skip is not None and path.resolve() == skip:
            continue
        found.append(path)
    return found


def is_generated_index(lines: list[str]) -> bool:
    """Whether the file's first non-blank line is the generated-index marker.

    Recognised by identity rather than by path: a generated index is a
    corpus-shaped markdown file that legitimately carries no frontmatter, and
    ``--index`` may name a different location than the one already on disk.
    """
    for line in lines:
        if line.strip():
            return line.strip() == INDEX_MARKER
    return False


def load(path: Path, root: Path, report: Report, survey: bool = False) -> Doc | None:
    """Read and parse one document.

    Args:
        path: The file to read.
        root: The corpus root, for relative naming in messages.
        report: Collector for anything the contract forbids.
        survey: When true, a missing or malformed frontmatter block is not an
            error and the document is still returned for structural analysis.
            A pre-conversion corpus has no frontmatter by definition, so
            refusing to look at it would make the survey useless exactly where
            it is needed.

    Returns:
        The parsed document, or ``None`` when it is a generated index or could
        not be read. An unreadable file is reported and skipped rather than
        aborting the run.
    """
    rel = str(path.relative_to(root))
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        report.error(f"{rel}: cannot read ({exc})")
        return None
    lines = text.splitlines()
    if is_generated_index(lines):
        return None
    status, block, body_start = split_frontmatter(lines)
    if status != "ok":
        if not survey:
            detail = (
                "no frontmatter block"
                if status == "absent"
                else "frontmatter opened but never closed"
            )
            report.error(f"{rel}: {detail}")
            return None
        return Doc(path=path, rel=rel, lines=lines, front={}, body_start=0)
    front, parse_errors = parse_frontmatter(block)
    if not survey:
        for message in parse_errors:
            report.error(f"{rel}: {message}")
    return Doc(path=path, rel=rel, lines=lines, front=front, body_start=body_start)


def render_survey(docs: list[Doc]) -> str:
    """Render the pre-conversion inventory that conversion Phase 1 needs.

    Structure only -- line counts, sections, and which sections are fork
    candidates. Implicit ownership and lifecycle live in prose and are the
    reader's job, not this script's.
    """
    lines: list[str] = []
    for doc in sorted(docs, key=lambda d: d.rel):
        state = "frontmatter present" if doc.front else "no frontmatter"
        sections = find_sections(doc)
        lines.append(
            f"{doc.rel} -- {len(doc.lines)} lines, {state}, {len(sections)} sections"
        )
        for heading, _, length in sections:
            flag = "FORK" if length > SECTION_WARN_LINES else "    "
            lines.append(f"  {flag}  {length:>5}  {heading}")
        lines.append("")
    return "\n".join(lines)


def usage_error(root: Path, index: Path | None, survey: bool) -> str | None:
    """Return a usage-error message, or None when the arguments are usable.

    Validated before any file is read, so a mistyped path fails immediately
    rather than after a full corpus walk.
    """
    if not root.is_dir():
        return f"{root} is not a directory"
    if index is not None and not index.parent.is_dir():
        return f"--index directory {index.parent} does not exist"
    if survey and index is not None:
        return "--survey does not write an index"
    return None


def run_contract_checks(docs: list[Doc], report: Report, index: Path | None) -> None:
    """Run every contract check over the corpus and regenerate the index."""
    for doc in docs:
        check_fields(doc, report)
        check_length(doc, report)
        check_amendments(doc, report)
    check_ownership(docs, report)
    if len(docs) >= 2 and index is None:
        report.warn(
            "corpus has 2+ documents and no index was generated; re-run with --index"
        )
    if index is not None:
        write_index(index, render_index(docs), report)


def emit(report: Report, count: int, quiet: bool, survey: bool) -> int:
    """Print the findings and return the process exit status."""
    for message in report.errors:
        print(f"ERROR {message}")
    if not quiet:
        for message in report.warnings:
            print(f"WARN  {message}")
    if survey:
        print(f"{count} document(s) surveyed")
    else:
        print(
            f"\n{count} document(s), {len(report.errors)} error(s), "
            f"{len(report.warnings)} warning(s)"
        )
    return EXIT_CONTRACT_ERRORS if report.failed else EXIT_OK


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser."""
    parser = argparse.ArgumentParser(
        description="Validate a design-forge corpus and regenerate its index."
    )
    parser.add_argument("root", type=Path, help="directory holding the corpus")
    parser.add_argument(
        "--index",
        type=Path,
        default=None,
        help="path to write the generated index to (omit to skip generation)",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="report errors only, suppress warnings",
    )
    parser.add_argument(
        "--survey",
        action="store_true",
        help=(
            "pre-conversion inventory: report structure and ceilings only, "
            "treating absent frontmatter as expected rather than as an error"
        ),
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    """Run the checker.

    Returns:
        ``0`` when no contract error was found, including when only warnings
        were, because ceilings never block. ``1`` on contract errors. ``2`` on
        a usage problem, which is the caller's fault rather than the corpus's.
    """
    args = build_parser().parse_args(argv)
    root: Path = args.root
    index: Path | None = args.index

    problem = usage_error(root, index, args.survey)
    if problem is not None:
        print(f"error: {problem}", file=sys.stderr)
        return EXIT_BAD_USAGE

    report = Report()
    skip = index.resolve() if index is not None else None
    docs = [
        doc
        for path in collect(root, skip)
        if (doc := load(path, root, report, survey=args.survey)) is not None
    ]

    if args.survey:
        print(render_survey(docs))
    else:
        run_contract_checks(docs, report, index)

    return emit(report, len(docs), quiet=args.quiet, survey=args.survey)


if __name__ == "__main__":
    raise SystemExit(main())
